name: Build Project
on: [push]
jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: windows-2022
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: CMake Win32
        shell: pwsh
        run: cmake -G "Visual Studio 17 2022" -A Win32 CMakeLists.txt -B Win32

      - name: Build Win32
        shell: pwsh
        run: cmake --build Win32 --target Multi-Segmentor Multi-Segmentor-Test --config Release && mv Win32/Release/* Win32

      - name: CMake x64
        shell: pwsh
        run: cmake -G "Visual Studio 17 2022" -A x64 CMakeLists.txt -B x64

      - name: Build x64
        shell: pwsh
        run: cmake --build x64 --target Multi-Segmentor Multi-Segmentor-Test --config Release && mv x64/Release/* x64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            Win32/Multi-Segmentor.exe
            Win32/Multi-Segmentor-Test.exe
            x64/Multi-Segmentor.exe
            x64/Multi-Segmentor-Test.exe
